### ISSUE TITLE
It seems future import doesn't work for multiple imports at time (one line)

### ISSUE THREAD

**Issue by humitos** [xZise/flake8-future-import#9] opened 2016-09-22 18:41 UTC
Here is my example to show the problem.

The Python file:

``` python
# -*- coding: utf-8 -*-


from __future__ import division, print_function, unicode_literals

print('Flake8 Future Import Test')
```

As you can see, I have 3 imports from `__future__`. Then I run the flake8 command with the plugin installed but it says that I'm not importing "division", "print_function" and "unicode_literals", which is wrong:

```
$ flake8 flake_future_import_test.py 
flake_future_import_test.py:0:1: I002 no configuration found (.isort.cfg or [isort] on setup.cfg)
flake_future_import_test.py:1:1: D100 Missing docstring in public module
flake_future_import_test.py:1:1: FI10 __future__ import "division" missing
flake_future_import_test.py:1:1: FI15 __future__ import "generator_stop" missing
flake_future_import_test.py:1:1: FI16 __future__ import "nested_scopes" missing
flake_future_import_test.py:1:1: FI14 __future__ import "unicode_literals" missing
flake_future_import_test.py:1:1: FI12 __future__ import "with_statement" missing
flake_future_import_test.py:1:1: FI11 __future__ import "absolute_import" missing
flake_future_import_test.py:1:1: FI17 __future__ import "generators" missing
flake_future_import_test.py:1:1: FI13 __future__ import "print_function" missing
```

My flake8 and plugins versions:

```
$ flake8 --version
3.0.4 (flake8_meiqia: 0.0.4, flake8_isort: 2.0, flake8-blind-except: 0.1.1, pycodestyle: 2.0.0, pyflakes: 1.2.3, flake8_quotes: 0.8.1, flake8-exact-pin: 0.0.1, flake-mutable: 1.0.4, flake8-todo: 0.6, flake8-docstrings: 1.0.2, pydocstyle: 1.0.0, flake8-string-format: 0.2.3, flake8-comprehensions: 1.2.1, flake8-debugger: 1.4.0, flake8-future-import: 0.4.3, naming: 0.4.1, flake8_coding: 1.3.0, flake8-print: 2.0.2, mccabe: 0.5.2, flake8_pep3101: 0.1, flake8_builtins: 0.1, flake8_commas: 0.1.6, flake8-tidy-imports: 1.0.2) CPython 2.7.12 on Linux
```

Thanks!

**Comment by xZise** [comment] 2016-11-09 09:35
Sorry for the late reply, but just now noticed that I hadn't responded. Anyway I tried to reproduce your bug but I can't. I tried it with Flake8 3.0.4 using Python 2.7.8 and 3.5.2. Also on Python 3.5.2 I tried it with Flake8 2.6.2, but every time I get the expected response:

```
$ flake8 --version
3.0.4 (pycodestyle: 2.0.0, pyflakes: 1.2.3, mccabe: 0.5.2, flake8-future-import: 0.4.3) CPython 2.7.8 on Linux
$ flake8 multi-line.py 
multi-line.py:1:1: FI15 __future__ import "generator_stop" missing
multi-line.py:1:1: FI16 __future__ import "nested_scopes" missing
multi-line.py:1:1: FI12 __future__ import "with_statement" missing
multi-line.py:1:1: FI11 __future__ import "absolute_import" missing
multi-line.py:1:1: FI17 __future__ import "generators" missing
multi-line.py:4:1: FI50 __future__ import "division" present
multi-line.py:4:1: FI53 __future__ import "print_function" present
multi-line.py:4:1: FI54 __future__ import "unicode_literals" present
```

Maybe another plugin is causing the issue?

**Comment by humitos** [comment] 2017-06-25 17:15
I'm not following you. Why do you say that's the expected response? You are receiving:

    multi-line.py:4:1: FI53 __future__ import "print_function" present

for example, but the `print_function` is already imported from future.

**Comment by xZise** [comment] 2017-06-28 12:39
The plugin works both ways. It is listing imports which are present as well, which can be handy to forbid certain imports. So in my case it reports the three imports as "present" (they exist in the code). The other imports are reported as "missing".

In your output the plugin is reporting that the existing ones are missing though, which isn't correct. But unfortunately I cannot reproduce this.

**Comment by humitos** [comment] 2017-06-28 12:43
Oh! I will keep researching.

From your output (and the one I pasted), I didn't notice that it says `present`. Sorry about that and thank you for your answer.

**Comment by xZise** [comment] 2022-08-05 18:18
Hi, as this issue is quite old and wasn't reproducible I'm going to close it. Feel free to reopen it in case there is still an issue.

**Closed by xZise** 2022-08-05 18:18 UTC
