### ISSUE TITLE
with_statement not deactivated by min-version = 2.6

### ISSUE THREAD

**Issue by jayvdb** [xZise/flake8-future-import#7] opened 2016-05-30 13:18 UTC
`with_statement` is mandatory in Python 2.6, but setting `min-version = 2.6` does not allow `with_statement` to be omitted.

See https://gerrit.wikimedia.org/r/#/c/291729/ 

It looks like https://github.com/xZise/flake8-future-import/blob/master/flake8_future_import.py#L131 should be using `feature.mandatory <= self.min_version`.

**Comment by xZise** [comment] 2016-05-30 14:47
Agreed, that seems sensible. I hope that I can release 0.4.1 within a few hours.

Funny thing is, that I looked through the coverage and noticed that the minimum version handling wasn't actually tested. I thought about adding it but decided that it probably wasn't important enough. How wrong I was, I hope that this bug isn't too disruptive.

**Comment by jayvdb** [comment] 2016-05-30 15:04
No drama.
The addition of the new codes is what broke our build env, and I didn't immediately get that relnote "Add two older future imports" meant two new codes needed to be ignored.
Given the incredibly low likelihood that your typical customer is targeting 2.3 or 2.2, perhaps set the default min-version = 2.4, so those new codes are automatically ignored by default, which means this release wont break anyones build env.

**Comment by xZise** [comment] 2016-05-30 15:32
It seems sensible, but the issue is that it will not consider features after the introduction, which would basically just only check `__future__.division`. The reason behind this is that any feature introduced after that version cannot be used anyway. Although I need to verify that it still complains when they exist.

So it either considers features introduced after that min version or there is another mechanism to ignore codes by default, but considering that `--ignore` is already available, I think this might have to wait for a future version.

Anyway, apart from verifying that it'll complain when to new features are used, I think there is a patch ready (+test) for 0.4.1.

**Comment by xZise** [comment] 2016-05-30 18:24
Okay I'll close this issue as the original issue has been resolved. At the moment I have troubles uploading it to PyPI though, but apart from that 0.4.1 should be up soon.

**Closed by xZise** 2016-05-30 18:24 UTC
